// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

contract DePinRegistry is Ownable {
    using ECDSA for bytes32;
    using MessageHashUtils for bytes32;

    struct Device {
        bool isRegistered;
        address owner;
        uint256 lastHeartbeat;
        uint256 totalUptime;
    }

    mapping(address => Device) public devices;
    uint256 public constant REWARD_PER_HEARTBEAT = 10 * 10**18; // 10 Tokens
    uint256 public constant HEARTBEAT_WINDOW = 1 hours;

    event DeviceRegistered(address indexed device, address indexed owner);
    event HeartbeatProcessed(address indexed device, uint256 timestamp);

    constructor() Ownable(msg.sender) {}

    function registerDevice(address _device, address _owner) external onlyOwner {
        require(!devices[_device].isRegistered, "Already registered");
        devices[_device] = Device(true, _owner, 0, 0);
        emit DeviceRegistered(_device, _owner);
    }

    /**
     * @dev Process a signed heartbeat from a hardware device.
     * @param _device The address associated with the hardware's public key.
     * @param _timestamp The time the data was generated.
     * @param _signature The ECDSA signature generated by the device.
     */
    function submitHeartbeat(
        address _device,
        uint256 _timestamp,
        bytes calldata _signature
    ) external {
        require(devices[_device].isRegistered, "Device not in registry");
        require(_timestamp > devices[_device].lastHeartbeat, "Stale timestamp");
        require(_timestamp <= block.timestamp, "Future timestamp");

        // Verify the signature was created by the device itself
        bytes32 messageHash = keccak256(abi.encodePacked(_device, _timestamp)).toEthSignedMessageHash();
        address signer = messageHash.recover(_signature);
        
        require(signer == _device, "Invalid signature");

        // Update device state
        devices[_device].lastHeartbeat = _timestamp;
        devices[_device].totalUptime += 1;

        emit HeartbeatProcessed(_device, _timestamp);
    }
}
